Support python 2
ankitjain28may/getit pull request #6
Opened 2017-10-30 09:42 UTC by simba3447

This pull request is related to the issue [#5](https://github.com/ankitjain28may/getit/issues/5).
I changed that urlopen is imported from urllib2 when python version is 2.

2017-10-30 11:47 UTC, ankitjain28may requested changes

2017-10-30 11:47 UTC, ankitjain28may commented on getit/getit.py
>  init()
check line 249, You will find `input()` syntax which is available only in python3

2017-10-30 12:55 UTC, ankitjain28may requested changes
It shows this error
```
  File "getit.py", line 123
SyntaxError: Non-ASCII character '\xe2' in file getit.py on line 124, but no encoding declared; see http://python.org/dev/peps/pep-0263/ for details
```

2017-10-30 14:32 UTC, simba3447 commented
I don't see that error, but I added encoding declaration. Can you check if the error occurs again?

2017-11-15 07:28 UTC, ankitjain28may approved these changes
LGTM

2017-11-15 07:28 UTC, merged